version: '3.3'
services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mailer
    ports:
      - 5432:5432
    container_name: postgres
