name: run tests
on: 
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    
    steps:
      - name: Copy repository
        uses: actions/checkout@v2
      
      - name: Use Node.js 
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.x
          architecture: x64

      - name: Install npm dependencies
        run: npm ci
      
      - name: Lint code
        run: npm run lint
      
      - name: Run tests
        run: npm run test:build